// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACKGnv2zgOKWagxW2XDAPnr2ItzmB7290',
    appId: '1:1004545666244:web:087a241015eafc7664ad91',
    messagingSenderId: '1004545666244',
    projectId: 'neural-cathode-372804',
    authDomain: 'neural-cathode-372804.firebaseapp.com',
    storageBucket: 'neural-cathode-372804.appspot.com',
    measurementId: 'G-H9MYR9N7LP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8A51bFZ6Hs_p8eYp7rlXx0hgjMSM0IrU',
    appId: '1:1004545666244:android:8dcea901b6bd9aa764ad91',
    messagingSenderId: '1004545666244',
    projectId: 'neural-cathode-372804',
    storageBucket: 'neural-cathode-372804.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY12-1yNFODWymT7vCLsEUy_-Y0-3ATj0',
    appId: '1:1004545666244:ios:541d97686b6afa4664ad91',
    messagingSenderId: '1004545666244',
    projectId: 'neural-cathode-372804',
    storageBucket: 'neural-cathode-372804.appspot.com',
    iosClientId: '1004545666244-i634uue27pvmmpo7ls14rhddk9gi04ea.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );
}
